// Auto-generated by scripts/generate-discovered-images.mjs — do not edit by hand.
export const DISCOVERED_PRODUCT_PNGS = [
  "7.png",
  "cosulet-fata.png",
  "cosulet-spate.png",
  "momitoare-3-spite.png",
  "momitoare-dunare.png",
  "momitoare-grele.png",
  "momitoare-longcast.png",
  "momitoare-medii.png",
  "momitoare-usoare.png",
  "plumb-bag.png",
  "plumb-fix-tija.png",
  "plumb-fix-vartej.png",
  "plumb-inline-fara-tija.png",
  "plumb-para-inline.png",
  "plumb-para.png",
  "plumb-pasta-longcast.png",
  "plumb-pasta.png",
  "plumb-sondare.png",
  "plumbi-lacrima.png",
  "plumbi-trident-1.png",
  "plumbi-trident-2.png"
] as const;

export type DiscoveredProductPng = (typeof DISCOVERED_PRODUCT_PNGS)[number];
